#!/bin/bash

SPACECREATOR=spacecreator.AppImage

if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi
echo -e "Welcome to ${COLORON}TASTE${COLOROFF}"

INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"


run_space_creator () {
    echo -e "${INFO} Running Space Creator with $1"
    $SPACECREATOR $1 interfaceview.xml

}
# To determine if we are in an existing project folder
PROJECT_FILE=$(find *.pro 2>/dev/null)

# If the project file already exist, directly run the gui
if [ -f "$PROJECT_FILE" ]
then
    run_space_creator $PROJECT_FILE
    exit $?
fi

# New project: was the script called with "init" ( = don't run any gui just setup the project files)
if [ "$1" == "init" ]
then
   # With "init", a folder (project name) should be given as parameter
   new_folder="$2"
else
   # New project, interactive session: prompt user for project name
   echo -e "${INFO} A new TASTE Space Creator project folder will be created (use Ctrl-C to cancel)"
   read -p "Please enter a name for the new project folder: " new_folder
fi

# Project folder must start with a letter
if [[ "$new_folder" =~ ^[A-Za-z].* ]]
then
    if [ -d "$new_folder" ]
    then
        echo -e "${ERROR} Aborting - a folder with that name already exists"
        exit 1
    else
        mkdir "$new_folder"
        cd "$new_folder"
        touch InterfaceView.aadl
        PROJECT_FILE="$new_folder".pro
        PROJECT_NAME="$new_folder"
    fi
else
    echo -e "${ERROR} Aborting - The project name is invalid. Hint: first character shall be a letter."
    exit 1
fi

# Define strings to create Spacecrator's .pro.user config file:
BUILD_DIRECTORY=$(pwd)
# The UUID are not random, they relate to the version of Qt creator
UUID1="bfe30b91-dafe-4269-b7dc-07a3ac6ce17c"  # AppImage version
UUID2="6d650885-2dda-4f6a-b4fa-1fabe64f392b"  # Kit of the AppImage

#  Create the main Makefile
echo "KAZOO?=kazoo
SPACECREATOR?=spacecreator.AppImage
# Here you can specify custom compiler/linker flags, and add folders containing
# external code you want to compile and link for a specific partition.
# Use upper case for the partition name:
# export <PARTITIONNAME>_USER_CFLAGS=...
# export <PARTITIONNAME>_USER_LDFLAGS=...
# export <PARTITIONNAME>_EXTERNAL_SOURCE_PATH=

# Get the list of ASN.1 files from Space Creator project file:
DISTFILES=\$(shell qmake $PROJECT_FILE -o /tmp/null 2>&1)
ASN1_FILES=\$(shell find \${DISTFILES} 2>/dev/null | egrep '\.asn\$\$|\.asn1\$\$')

all:	c

c:	work/glue_built
	\$(MAKE) -C work

# Simulation target (experimental)
simu:	InterfaceView.aadl DeploymentView.aadl DataView.aadl ConcurrencyView_Properties.aadl
	\$(KAZOO) -t SIMU --glue --gw
	\$(MAKE) -C work

skeletons:
	\$(MAKE) work/skeletons_built

work/skeletons_built:	InterfaceView.aadl DataView.aadl
	\$(KAZOO) --gw -o work
	\$(MAKE) -C work dataview
	touch \$@

work/glue_built:	InterfaceView.aadl DeploymentView.aadl DataView.aadl ConcurrencyView_Properties.aadl
	\$(KAZOO) -p --glue --gw -o work
	touch \$@

InterfaceView.aadl:	interfaceview.xml
	\$(SPACECREATOR) --aadlconverter  -o \$^ -t \$(shell taste-config --prefix)/share/xml2aadl/interfaceview.tmplt -x \$@

DeploymentView.aadl:	interfaceview.xml
	# Create/update a deployment view for Linux target (to be removed when we have a DV editor)
        \$(SPACECREATOR) --aadlconverter  -o \$^ -t \$(shell taste-config --prefix)/share/xml2dv/interfaceview.tmplt -x \$@ || exit 1

DataView.aadl: \${ASN1_FILES}
	taste-update-data-view \$^

clean:
	rm -rf work/build
	rm -f work/glue_built work/skeletons_built
	find work -type d -name \"wrappers\" -exec rm -rf {} +
	find work -type d -name \"*_GUI\" -exec rm -rf {} +

.PHONY: clean skeletons c simu
" > Makefile

# Create Space Creator's project file
# the message($$DISTFILE) is used to display on screen the list
# of project files (to get the list of ASN.1 files for taste-update-dataview)
echo "TEMPLATE = lib
CONFIG -= qt
CONFIG += generateC

DISTFILES += $PROJECT_NAME.asn
DISTFILES += $PROJECT_NAME.acn
DISTFILES += $PROJECT_NAME.msc
DISTFILES += interfaceview.xml
#include(handleAsn1AcnBuild.pri)
include(work/taste.pro)
message(\$\$DISTFILES)
" > $PROJECT_FILE

# Create a default interface view
echo "<InterfaceView asn1file=\"$PROJECT_NAME.asn\">
<Comment name=\"Welcome to TASTE!\n============\n\nRight click to add a function, and use Ctrl-Click to connect functions together.\n\nYou can split the screen in multiple windows using Ctrl-E-3\">
    <Property name=\"Taste::coordinates\" value=\"4800 5100 46100 20700\"/>
</Comment>

</InterfaceView>" > interfaceview.xml

# Create default work folder
mkdir -p work
touch work/taste.pro

# Create empty MSC file
echo "mscdocument $PROJECT_NAME /* MSC AND */;
    language ASN.1;
    data $PROJECT_NAME.asn;

/* CIF MSCDOCUMENT (0, 0) (4200, 2300) */

mscdocument Nominal /* MSC LEAF */;

msc $PROJECT_NAME;
endmsc;
endmscdocument;
endmscdocument;" > $PROJECT_NAME.msc

# Create Qt Creator's XML Configuration file
cp -f $(taste-config --prefix)/bin/space_creator_config.xml $PROJECT_FILE.user
sed -i "s,BUILD_DIRECTORY,$BUILD_DIRECTORY," $PROJECT_FILE.user
sed -i "s/UUID1/$UUID1/" $PROJECT_FILE.user
sed -i "s/UUID2/$UUID2/" $PROJECT_FILE.user

# Create mandatory ConcurrencyView_Properties.aadl for kazoo
if [ ! -f ConcurrencyView_Properties.aadl ]
then
    touch ConcurrencyView_Properties.aadl
fi

# Create a default data view (use pre-made DataView.aadl to speed up)
echo -e "${INFO} Creating a default ASN.1 data model."
cp -f $(taste-config --prefix)/bin/space-creator-dataview.aadl DataView.aadl
sed -i "s/MD5ACN/$MD5ACN/" DataView.aadl
sed -i "s/MD5ASN/$MD5ASN/" DataView.aadl
sed -i "s/PROJECTNAME/$PROJECT_NAME/" DataView.aadl
NONINTERACTIVE=1 ONLY_ASN=1 taste-create-data-view "$PROJECT_NAME"


if [ "$1" == "init" ]
then
    echo -e "${INFO} Done. You can run 'space-creator' from the project folder to open the editor"
    echo -e "${INFO} 'make skeletons' to create the skeletons or just 'make' to build everything."
else
    run_space_creator $PROJECT_FILE
fi
