#!/bin/bash
# TASTE User Code Editor
# Depending on the implementation language, launch the corresponding code editor
# Script (c) Maxime Perrotin / ESA 2021
# Supported languages: C, Ada, SDL, C++, GUI (Python)
# Logging with colors (only in a terminal)
SPACECREATOR=spacecreator.AppImage

if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi
INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"

taste-xml-to-aadl || exit 1

# Space Creator uses 2 attributes to set the language depending if it is
# a normal function ($1) or a function type ($2). The other argument will be
# an empty string, which has to be skipped. We use the shift operator for that.
LANG=$1
if [[ $LANG == "" ]]
then
    shift
    LANG=$1
    FNAME=$2
else
    FNAME=$3
fi

if [[ $LANG != "C" && $LANG != "Ada" && $LANG != "SDL" && $LANG != "CPP" && $LANG != "GUI" && "$LANG" != "Blackbox_Device" ]]
then
    echo  -e "${ERROR} First argument must be C, CPP, Ada, SDL, GUI or Blackbox_C, and not \"$LANG\""
    exit 1
fi

# Check if the project works with kazoo. If so, use the makefile rule to edit the code
if [[ -f Makefile && $(grep KAZOO Makefile) != "" ]]
then
    FOLDER=work/"${FNAME,,}"/"$LANG"
    if [ ! -d "${FOLDER}" ]
    then
        echo -e "${ERROR} Folder missing: ${FOLDER} (skeleton generation failed?!)"
        exit 1
    fi

    # Text source code can be edited directly from within space creator
    cd "${FOLDER}"
    if [[ $LANG == "C" ]]
    then
        SOURCE_FILE=src/"${FNAME,,}".c
    elif [[ $LANG == "Ada" ]]
    then
        SOURCE_FILE=src/"${FNAME,,}".adb
    elif [[ $LANG == "CPP" ]]
    then
        SOURCE_FILE=src/"${FNAME,,}".cc
    elif [[ $LANG == "GUI" ]]
    then
        SOURCE_FILE=src/UserWidgets.py
    else
        make edit || exit 1
        exit 0
    fi

    # Check that source code actually exists, then edit in Qt Creator
    if [ ! -f "${SOURCE_FILE}" ]
    then
        echo -e "${ERROR} File missing: ${SOURCE_FILE} (skeleton generation failed?!)"
        exit 1
    else
        $SPACECREATOR -pid $PPID ${SOURCE_FILE}
        exit 0
    fi
else
    echo -e "${ERROR} Missing Makefile or project not supported by Kazoo"
    exit 1 
fi

