#!/bin/bash -e

# TASTE MSC Editor
# Edit a MSC file

if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi

INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"

MSC_FILENAME=$1

echo -e "${INFO} Opening MSC Editor..."
echo -e "${INFO} Filename: ${MSC_FILENAME}"

EDITOR="spacecreator.AppImage --MSCeditor"


if [ -z $NONINTERACTIVE ]
then
    $EDITOR -m $MSC_FILENAME
fi

