#!/bin/bash
# This script uses the tools from viking SW to convert MSC files to Python
# User may pass several MSC files as parameters
if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi
INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"

if [ -f /.dockerenv ]
then
    export NO_CLEANUP=1
    export APPIMAGE_EXTRACT_AND_RUN=1
fi
CONVERTER="spacecreator.AppImage --mscconverter"

echo -e "${INFO} MSC to Python Converter (c) 2020 European Space Agency / Maxime Perrotin"

for f in $@
do
    if [ ! -f "$f" ]
    then
        echo -e "${ERROR} File not found: ${f}"
    else
        msc_filename=$(readlink -e "$f")
        python_filename="${f%.*}.py"
        if [ -f "$python_filename" ]
        then
            if [ "$msc_filename" -nt "$python_filename" ]
            then
                backup_filename="${f%.*}.py.bak"
                cp -f ${python_filename} ${backup_filename}
                echo -e "${INFO} Replacing existing Python file: ${python_filename} (older saved as ${backup_filename})"
                $CONVERTER -m "${msc_filename}" -x "${python_filename}" -t $(taste-config --prefix)/share/msc/msc2py/mscmodel.tmplt
            else
                echo -e "${INFO} Ignoring ${msc_filename} because ${python_filename} is more recent"
            fi
        else
            echo -e "${INFO} Transforming file: ${msc_filename} to ${python_filename}"
            $CONVERTER -m "${msc_filename}" -x "${python_filename}" -t $(taste-config --prefix)/share/msc/msc2py/mscmodel.tmplt
        fi
    fi
done


