#!/bin/bash
# TASTE User Code Editor
# Depending on the implementation language, launch the corresponding code editor
# Script (c) Maxime Perrotin / ESA 2021
# Supported languages: C, Ada, SDL, C++, GUI (Python)
# Logging with colors (only in a terminal)
SPACECREATOR=spacecreator.AppImage

if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi
INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"

taste-xml-to-aadl || exit 1


if [[ $1 != "C" && $1 != "Ada" && $1 != "SDL" && $1 != "CPP" && $1 != "GUI" && "$1" != "Blackbox_Device" ]]
then
    echo  -e "${ERROR} First argument must be C, CPP, Ada, SDL, GUI or Blackbox_C"
    exit 1
fi

# Check if the project works with kazoo. If so, use the makefile rule to edit the code
if [[ -f Makefile && $(grep KAZOO Makefile) != "" ]]
then
    FOLDER=work/"${2,,}"/"$1"
    if [ ! -d "${FOLDER}" ]
    then
        echo -e "${ERROR} Folder missing: ${FOLDER} (skeleton generation failed?!)"
        exit 1
    fi

    # Text source code can be edited directly from within space creator
    cd "${FOLDER}"
    if [[ $1 == "C" ]]
    then
        SOURCE_FILE=src/"${2,,}".c
    elif [[ $1 == "Ada" ]]
    then
        SOURCE_FILE=src/"${2,,}".adb
    elif [[ $1 == "CPP" ]]
    then
        SOURCE_FILE=src/"${2,,}".cc
    elif [[ $1 == "GUI" ]]
    then
        SOURCE_FILE=src/UserWidgets.py
    else
        make edit || exit 1
        exit 0
    fi

    # Check that source code actually exists, then edit in Qt Creator
    if [ ! -f "${SOURCE_FILE}" ]
    then
        echo -e "${ERROR} File missing: ${SOURCE_FILE} (skeleton generation failed?!)"
        exit 1
    else
        $SPACECREATOR -pid $PPID ${SOURCE_FILE}
        exit 0
    fi
else
    echo -e "${ERROR} Missing Makefile or project not supported by Kazoo"
    exit 1 
fi

