/* C++ Body file for function type Air_Device
 * Generated by TASTE on 2020-04-29 11:05:33
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Poll_Device, Write_to_Device
 * Required interfaces : Received_Data
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 79210 62203 130390 105028
 *   |_ Taste::is_Component_Type = true
 * Timers              : 
 */

#include "air_device.h"

// Include Context Parameters (constants defined in the Interface View)
#include "Context-air-device.h"

void air_device::startup()
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Air_Device] Startup");
}

void air_device::Poll_Device(void)
{
   // Write your code here
}
void air_device::Write_to_Device
      (const asn1SccData_Stream *IN_stream)

{
   // Write your code here
}
